# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bddc3edc6a63be5598927604d22dc86e3665f6c713102273facc1f84d8973ffad133444f23530ac9e87505291254e34dc7cea55ef27f639c5309c509105be9e

test:
  secret_key_base: d033672b016745b83a6977ce6f3fa3ba4d1425c8da2d731db6fc037a2606be38e94cfa43deed6239f790b608683c27898d4d9e9e1279b6128d5dfe1fbe6d652a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
